myItems = {
    'clothes_up': {
        1: {
            'name': 'Футболка Hedricy',
            'size': 'XL',
            'color': 'синий',
            'price': '1400 руб',
            'buyDate': '17.03.2017',
            'buyPlace': "покупал в Ухте",
            'grade': 'На улицу, но не парадная',
            'actual': 'в наличии',
            'photo': ['clothes_up/clothes_up_1.jpg'],
            'description': `Футболка синяя Hedricy, надпись wear denim jeans black. Покупал в марте 2017, когда приезжал в Ухту.`,
        },
        2: {
            'name': "Футболка-поло O'STIN",
            'size': 'L/50-52',
            'color': 'белый',
            'price': '1400 руб (скидка по карте 299)',
            'buyDate': '28.04.2022',
            'buyPlace': "ТЦ Кольцо, магазин O'STIN на втором этаже",
            'grade': 'Парадно-выходная',
            'actual': 'в наличии',
            'photo': ['clothes_up/clothes_up_2.jpg'],
            'description': `Футболка-поло O'STIN белая в чёрный ромбик.
                            Ткань очень приятная гладкая, но воротничок плотный и от времени именно он страдает, засаливается.`,
        },
        3: {
            'name': "Футболка O'STIN",
            'size': 'L/50-52',
            'color': 'индиго',
            'price': '1199 руб',
            'buyDate': '27.06.2022',
            'buyPlace': "ТЦ Кольцо, магазин O'STIN на втором этаже",
            'grade': 'Парадно-выходная',
            'actual': 'в наличии',
            'photo': ['clothes_up/clothes_up_3.jpg'],
            'description': `Футболка O'STIN цвета индиго (оттенок синего) с бело-жёлтой надписью Explorer Safari
                            Discover Wild Expedition.`,
        },
        4: {
            'name': "Футболка Familia",
            'size': 'XL',
            'color': 'тёмно-серый',
            'price': '999 руб',
            'buyDate': '27.06.2022',
            'buyPlace': "ТЦ Парк Хаус, магазин Familia на втором этаже",
            'grade': 'Парадно-выходная',
            'actual': 'в наличии',
            'photo': ['clothes_up/clothes_up_4.jpg'],
            'description': `Футболка Familia тёмно-серая с жёлтой надписью Cross Hatch.`,
        },
        5: {
            'name': "Термобельё Kipsta Dry 900 (верх)",
            'size': 'L',
            'color': 'чёрный',
            'price': '1299 руб',
            'buyDate': '06.10.2019',
            'buyPlace': "Казань, Ибрагимова 54, магазин Decathlon",
            'grade': 'спортивная',
            'actual': 'в наличии',
            'photo': ['clothes_up/clothes_up_5_1.jpg', 'clothes_up/clothes_up_5_2.jpg'],
            'description': `Верхняя часть комплекта термобелья. Предназначена для потоотведения и защиты от ветра, от
                            холода не защищает (не утеплённая). Очень плотно прилегает к телу.`,
        },
    },
    'clothes_down': {
        1: {
            'name': 'Штаны джоггеры',
            'size': '32/48',
            'color': 'тёмно-синий',
            'price': '3499 руб',
            'buyDate': '12.06.2023',
            'buyPlace': "ТЦ Кольцо, магазин O'STIN на втором этаже",
            'grade': 'Парадно-выходные',
            'actual': 'в наличии',
            'photo': ['clothes_down/clothes_down_1_1.jpg', 'clothes_down/clothes_down_1_2.jpg',
                      'clothes_down/clothes_down_1_3.jpg', 'clothes_down/clothes_down_1_4.jpg',
                      'clothes_down/clothes_down_1_5.jpg'],
            'description': `Хорошие штаны из плотной ткани, годятся для носки примерно до +5 градусов. Из минусов
                            отсутствует защита карманов, они открытые и из могут вывалиться вещи.`,
        },
        2: {
            'name': 'Брюки карго',
            'size': '32/48',
            'color': 'оливковый',
            'price': '3600 руб (скидка по карте 399)',
            'buyDate': '15.06.2022',
            'buyPlace': "ТЦ Кольцо, магазин O'STIN на втором этаже",
            'grade': 'Парадно-выходные',
            'actual': 'в наличии',
            'photo': ['clothes_down/clothes_down_2_1.jpg', 'clothes_down/clothes_down_2_2.jpg'],
            'description': `Хорошие брюки для носки до +5 градусов, однако за год ткань подозрительно сильно истёрлась,
                            как будто не очень прочная.`,
        },
        3: {
            'name': "Термобельё Kipsta Dry 900 (низ)",
            'size': 'L',
            'color': 'чёрный',
            'price': '1699 руб',
            'buyDate': '06.10.2019',
            'buyPlace': "Казань, Ибрагимова 54, магазин Decathlon",
            'grade': 'спортивная',
            'actual': 'в наличии',
            'photo': ['clothes_down/clothes_down_3.jpg'],
            'description': `Нижняя часть комплекта термобелья. Предназначена для потоотведения и защиты от ветра, от
                            холода не защищает (не утеплённая). Очень плотно прилегает к телу.`,
        },
        4: {
            'name': "Ортопедические стельки-супинаторы ORTO MIX",
            'size': '45',
            'color': 'бежевый',
            'price': '2904 руб',
            'buyDate': '07.07.2023',
            'buyPlace': "Ухта, Ленина 12/2, магазин ortokomi.com",
            'grade': 'медицинская',
            'actual': 'в наличии',
            'photo': ['clothes_down/clothes_down_4.jpg'],
            'description': `Хорошие ортопедические стельки для поддержки стопы.`,
        },
        5: {
            'name': "Шорты TRAVEL 100 FORCLAZ",
            'size': 'RU 50, EU 44, US M',
            'color': 'тёмно-серый',
            'price': '1799 руб',
            'buyDate': '30.06.2020',
            'buyPlace': "Казань, Ибрагимова 54, магазин Decathlon",
            'grade': 'Гуляночные',
            'actual': 'в наличии',
            'photo': ['clothes_down/clothes_down_5.webp'],
            'description': `Хорошие туристические походные шорты из крепкого материала.`,
        },
    },
    'clothes_boots': {
        1: {
            'name': 'Ботинки зимние Rieker F6814-16',
            'size': '45',
            'color': 'тёмно-синий',
            'price': '5350 руб + доставка 310',
            'buyDate': '02.02.2023',
            'buyPlace': 'Интернет-магазин rieker-moscow.ru',
            'grade': 'Парадно-выходные',
            'actual': 'в наличии',
            'photo': ['clothes_boots/clothes_boots_1_1.jpg', 'clothes_boots/clothes_boots_1_2.jpg',
                      'clothes_boots/clothes_boots_1_3.jpg', 'clothes_boots/clothes_boots_1_4.jpg',
                      'clothes_boots/clothes_boots_1_5.jpg'],
            'description': `Хорошие зимние ботинки, тёплые, материалы качественные, прочные. Из минусов только подошва -
                            скользит на льду несмотря на то, что с виду неплохой протектор.`,
        },
        2: {
            'name': 'Кроссовки Asics GT-2000 7',
            'size': '45',
            'color': 'чёрный',
            'price': '5927 руб (скидка 3573 по распродаже)',
            'buyDate': '06.09.2019',
            'buyPlace': "Интернет-магазин proball.ru",
            'grade': 'Гуляночные',
            'actual': 'в наличии',
            'photo': ['clothes_boots/clothes_boots_2_1.jpg', 'clothes_boots/clothes_boots_2_2.webp',
                      'clothes_boots/clothes_boots_2_3.jpg'],
            'description': `Хорошие беговые кроссовки, с поддержкой стопы для плоскостопых. Покупал для пробежек и на
                            повседнев (оригинал, не реплика). Очень много их носил (6-7 месяцев в году, иногда для
                            грязных работ), за 4 года подошва стопталась. Размер US12 (29,5 см), российский 45.`,
        },
        3: {
            'name': 'Кроссовки Asics Gel-Nimbus 18 Lite-Show',
            'size': '44,5',
            'color': 'асфальтовый/чёрный',
            'price': '7700 руб (скидка 4300 по распродаже)',
            'buyDate': '31.08.2017',
            'buyPlace': "Интернет-магазин runlab.ru",
            'grade': 'Рабочие',
            'actual': 'в наличии',
            'photo': ['clothes_boots/clothes_boots_3_1.jpg', 'clothes_boots/clothes_boots_3_2.jpg',
                      'clothes_boots/clothes_boots_3_3.jpg', 'clothes_boots/clothes_boots_3_4.jpg',
                      'clothes_boots/clothes_boots_3_5.jpg'],
            'description': `Хорошие беговые кроссовки, с поддержкой стопы для плоскостопых. Покупал для пробежек и на
                            повседнев (оригинал, не реплика). Очень сильно понравилась модель и внешний вид и скидка по
                            распродаже была очень большая, рискнул взять последний оставшийся размер 44,5. В итоге
                            кроссовки оказались отличные, но сильно пожалел, что взял не свой размер.`,
        },
        4: {
            'name': 'Ботинки демисезонные NH500 MID WP QUECHUA',
            'size': '45',
            'color': 'бежевый',
            'price': '3999 руб',
            'buyDate': '24.03.2021',
            'buyPlace': "Казань, Ибрагимова 54, магазин Decathlon",
            'grade': 'Гуляночные/парадно-выходные',
            'actual': 'в наличии',
            'photo': ['clothes_boots/clothes_boots_4_1.webp', 'clothes_boots/clothes_boots_4_2.webp',
                      'clothes_boots/clothes_boots_4_3.webp', 'clothes_boots/clothes_boots_4_4.webp',
                      'clothes_boots/clothes_boots_4_5.webp'],
            'description': `Отличные непромокаемые ботинки на огромной подошве, лужи любой глубины вообще не ощущаются.
                            Из минусов - не очень эластичные, жёсткие (так как создавались для горных походов) и при
                            ходьбе подошва чавкает.`,
        },
        5: {
            'name': 'Кроссовки Asics Novablast 3',
            'size': '46',
            'color': 'чёрный',
            'price': '20120 руб + 300 доставка',
            'buyDate': '16.07.2023',
            'buyPlace': "Интернет-магазин sport-marafon.ru",
            'grade': 'Парадно-выходные/беговые',
            'actual': 'в наличии',
            'photo': ['clothes_boots/clothes_boots_5_1.jpg', 'clothes_boots/clothes_boots_5_2.jpg',
                      'clothes_boots/clothes_boots_5_3.jpg', 'clothes_boots/clothes_boots_5_4.jpg',
                      'clothes_boots/clothes_boots_5_5.jpg', 'clothes_boots/clothes_boots_5_6.jpg',
                      'clothes_boots/clothes_boots_5_7.jpg', 'clothes_boots/clothes_boots_5_8.jpg',
                      'clothes_boots/clothes_boots_5_9.jpg'],
            'description': `Хорошие беговые кроссовки, очень мягкие и лёгкие (оригинал, не реплика). По размеру брал
                            как прошлые кроссовки этой фирмы - US12 29,5 см, но видимо у них размерный ряд изменился,
                            в этот раз на размер больше вышли. Но как раз хотел с запасом под ортопедическую стельку,
                            поэтому не вываливаюсь, свободного пространства в разумных пределах. Первая пробежка -
                            18.07.2023, хорошо себя показали.`,
        },
    },
    'books': {
        1: {
            'name': 'Django 3.0 Практика программирования веб-сайтов на Python',
            'author': 'Дронов А.В.',
            'buyDate': '08.02.2020',
            'buyPlace': 'Авито (Казань, лично встретился)',
            'year': 2020,
            'price': '1000 руб',
            'actual': 'в наличии',
            'pageCount': 704,
            'photo': ['books/books_1_front.jpg', 'books/books_1_back.jpg'],
            'description': `Покупал с рук на Авито в отличном состоянии (б/у несколько месяцев, практически не читали).<br>
                            Бумага плотная, но немного просвечивают страницы и краска текста имеет тенденцию смазываться,
                            поэтому читать можно лишь аккуратно держа за края, не ставя пальцы на текст. Переплёт мягкий,
                            но так как очень много страниц, то  не очень удобно держать книгу (стык страниц очень тугой,
                            не даёт полностью раскрыть книгу). Несмотря на примеры с кодом и пояснения книга больше
                            похожа на справочник, чем на учебник.`,
        },
        2: {
            'name': '"Трилогия желания" (Финансист, Титан, Стоик)',
            'author': 'Теодор Драйзер',
            'buyDate': '15.10.2022',
            'buyPlace': 'Авито (доставка из Магнитогорска)',
            'year': 2022,
            'price': '649 руб + 49 доставка Авито',
            'actual': 'в наличии',
            'pageCount': 1214,
            'photo': ['books/books_2_1.webp', 'books/books_2_2.webp'],
            'description': `Три тома в одной книге - Финансист, Титан, Стоик, покупал с Авито в идеальном состоянии.
                            Хорошая большая книга, очень много страниц, классная обложка (и сама иллюстрация и материал),
                            хорошее качество бумаги, краска не смазывается. Из минусов можно выделить, что страницы просвечивают
                            и из-за огромного количества страниц не очень удобно держать книгу в раскрытом состоянии (проблема
                            любой толстой книги).`,
        }
    },
    'furniture': {
        1: {
            'name': 'Комод Ронда',
            'color': 'ореховый/белый',
            'size': '80x42x82',
            'price': '3610 руб + 700 руб доставка',
            'buyDate': '25.05.2022',
            'buyPlace': 'Интернет-магазин gorodskaya-mebel.ru',
            'actual': 'в наличии',
            'photo': ['furniture/furniture_1_1.jpg', 'furniture/furniture_1_2.jpg'],
            'description': `Бюджетный комод Ронда, покупался в разобранном виде (как в ИКЕЕ). У ящиков панели белые,
                            остальной комод ореховый (цвет венге/дуб белфорд). В целом нормальные материалы, но
                            задняя стенка комода из тонкого листа ДСП + днища в ящиках так же из ДСП и из-за этого
                            прогибаются под большой тяжестью.`,
        },
        2: {
            'name': 'Стол-книжка Дублин 4061',
            'color': 'чёрный',
            'size': '85x99x71.5',
            'price': '3225 руб + доставка 400',
            'buyDate': '16.11.2018',
            'buyPlace': 'Интернет-магазин mobi-mebel.ru',
            'actual': 'в наличии',
            'photo': ['furniture/furniture_2_1.jpg', 'furniture/furniture_2_2.jpg', 'furniture/furniture_2_3.jpg',
                      'furniture/furniture_2_4.jpg'],
            'description': `Неплохой бюджетный стол-раскладушка, материалы нормальные, покупался в разобранном виде
                            (как в ИКЕЕ). Замечание только к ножкам, которые нужно прикручивать на саморезы, чтобы стол
                            в открытом виде стоял. Покупал для ПК.`,
        },
        3: {
            'name': 'Доска магнитно-маркерная TS86/C OZ',
            'color': 'белый',
            'size': '60x80',
            'price': '1193 руб',
            'buyDate': '14.03.2019',
            'buyPlace': 'Интернет-магазин kapitan-kazan.ru',
            'actual': 'в наличии',
            'photo': ['furniture/furniture_3_1.jpg', 'furniture/furniture_3_2.webp', 'furniture/furniture_3_3.webp'],
            'description': `Белая маркерная доска с деревянной рамкой (ECO, "2х3" Польша). Спустя год некоторые места
                            протёрлись и надписи даже после стирания остаются слегка заметны.`,
        },
        4: {
            'name': 'Диван Solsta',
            'color': 'чёрный',
            'size': '140x80x75',
            'price': '3999 руб + 1000 доставка',
            'buyDate': '10.09.2017',
            'buyPlace': 'Казань, ТЦ Мега, магазин ИКЕА',
            'actual': 'отдал',
            'end': '13.06.2022',
            'photo': ['furniture/furniture_4_1.jpeg', 'furniture/furniture_4_2.jpg'],
            'description': `Бюджетный диван-раскладушка, из плюсов разве что цена. В разложенном виде спишь почти на
                            полу, причём в разложенном виде он неровный, с перепадами. Материал ткани дешманский,
                            наполнитель тоже. Пользовался 1,5 года, потом после переезда на другую квартиру где была
                            кровать долго стоял пылился, 13.06.2022 отдал.`,
        },
    },
    'electronics': {
        1: {
            'name': 'Ноутбук 17.3 MSI GF76 Katana 11SC-853XRU',
            'color': 'чёрный',
            'price': '68399 руб',
            'buyDate': '07.01.2023',
            'buyPlace': 'Ухта, ТЦ Ярмарка, в магазине DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_1_1.webp', 'electronics/electronics_1_2.webp',
                      'electronics/electronics_1_3.webp', 'electronics/electronics_1_4.webp'],
            'description': `Full HD 1920x1080 144Гц. IPS. Intel Core i5-11400H. ядра: 6 (6 производительных)
                            (12 потоков). RAM 16 Гб, SSD 512 Гб Покупал в Ухте в Ярмарке, когда приезжал на новый год.`,
        },
        2: {
            'name': 'Ноутбук HP 17-y021ur',
            'color': 'чёрный',
            'price': '28206 руб + доставка 401',
            'buyDate': '16.06.2017',
            'buyPlace': 'Интернет-магазин torg-pc.ru',
            'actual': 'отдал',
            'end': '06.01.2023',
            'photo': ['electronics/electronics_2_1.jpg', 'electronics/electronics_2_2.jpg',
                      'electronics/electronics_2_3.jpg', 'electronics/electronics_2_4.jpg'],
            'description': 'Покупал в Советске (заказывал по почте). В январе 2023 отдал.',
        },
        3: {
            'name': 'Смартфон Xiaomi Redmi Note 8 Pro 128 Гб',
            'color': 'белый',
            'price': '17990 руб',
            'buyDate': '27.06.2020',
            'buyPlace': 'Ухта, проспект Ленина 22, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_3.jpg'],
            'description': `Подарок на день рождения. Предыдущий телефон ещё не разваливался, но изначально он
                            покупался как временный вариант, поэтому спустя 3 года решили его заменить.`,
        },
        4: {
            'name': 'Смартфон Huawei Honor 4C Pro 16 Гб',
            'color': 'кремовый',
            'price': '8999 руб',
            'buyDate': '10.08.2017',
            'buyPlace': 'Ухта, проспект Ленина 22, магазин DNS',
            'actual': 'отдал',
            'end': '23.08.2020',
            'photo': ['electronics/electronics_4_1.jpg', 'electronics/electronics_4_2.jpg'],
            'description': `Подарок на день рождения, покупали на подаренный ей на работе сертификат. Предыдущий
                            телефон уже разваливался, экран был разбитый и т.д. Бюджетный смартфон, купили как временный
                            вариант ("временный вариант" затянулся на 3 года). Внешний вид симпатичный и приятный на
                            ощупь, но в руке ощущается дешевизна пластика и при первом же падении на землю появилась
                            вмятина и скол. Железо и камера довольно слабые. В июне 2020 после покупки нового смартфона
                            передал в приют человека.`,
        },
        5: {
            'name': 'Смартфон Explay Flame 4 Гб',
            'color': 'белый',
            'price': '0 руб (обмен)',
            'buyDate': '01.02.2016',
            'buyPlace': 'Армия',
            'actual': 'отдал',
            'end': '01.09.2017',
            'photo': ['electronics/electronics_5_1.webp', 'electronics/electronics_5_2.webp'],
            'description': `В армии на день рождения сослуживца поменялись с ним телефонами (я ему свой старый
                            Samsung Galaxy S2 (трёхлетний и уже потрёпаный), он мне свой Explay Flame с треснутым
                            экраном с доплатой мне 2000). 10 августа 2017 купил новый телефон, этот отдал.`,
        },
        6: {
            'name': 'Флэшкарта PNY USB 3.0 64Гб',
            'color': 'чёрный',
            'price': '499 руб',
            'buyDate': '02.09.2022',
            'buyPlace': 'ТЦ Кольцо, магазин DNS на нулевом этаже',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_6_1.webp', 'electronics/electronics_6_2.webp'],
            'description': `Купил в DNS в ТЦ Кольцо (метро Площадь Тукая), старую флешку потерял, нужен был
                            накопитель для распечатки документов.`,
        },
        7: {
            'name': 'Флэшкарта Xiaomi USB 3.0/Type-C 1Тб',
            'color': 'серебистый',
            'price': '128 руб',
            'buyDate': '07.07.2023',
            'buyPlace': 'AliExpress',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_7_1.webp', 'electronics/electronics_7_2.webp'],
            'description': `Валера подарил, когда я в Ухту приезжал. Он заказывал с AliExpress по акции за 128 рублей.
                            Очень медленная, 15Гб скачалось на неё за 26 минут. Плюс понадобилось перепрошивать, портит файлы.`,
        },
        8: {
            'name': 'Смартфон Samsung Galaxy S2 16 Гб',
            'color': 'чёрный',
            'price': '18500 руб',
            'buyDate': '01.08.2012',
            'buyPlace': 'Ухта, проспект Ленина 22, магазин DNS',
            'actual': 'обменял',
            'end': '01.02.2016',
            'photo': ['electronics/electronics_8_1.webp', 'electronics/electronics_8_2.webp', 'electronics/electronics_8_3.webp'],
            'description': `Подарок на день рождения, старый телефон уже разваливался на части, на скотче держался.
                            Покупали в августе 2012 когда был в Ухте на каникулах. В армии на день рождения сослуживца
                            поменялись с ним телефонами.`,
        },
        9: {
            'name': 'Часы Kalenji W100 S',
            'color': 'чёрный',
            'price': '499 руб',
            'buyDate': '09.11.2019',
            'buyPlace': 'Казань, Ибрагимова 54, магазин Decathlon',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_9_1.jpg', 'electronics/electronics_9_2.webp'],
            'description': `Покупал ради секундомера, отлично прошли проверку временем. На вид может и не презентабельные,
                            но хорошо справляются и с водой и с ударами. Время корректирую раз в году.`,
        },
        10: {
            'name': 'Чайник Smile WK 5410',
            'color': 'чёрный',
            'price': '990 руб',
            'buyDate': '01.03.2019',
            'buyPlace': 'Интернет-магазин rbt.ru',
            'actual': 'отдал',
            'end': '13.12.2021',
            'photo': ['electronics/electronics_10.webp'],
            'description': `Бюджетный электрический чайник. Работал без нареканий, пока летом 2021 спустя 2 года
                            эксплуатации не начал сбоить, а в декабре 2021 окончательно сломался. Сдал на переработку.`,
        },
        11: {
            'name': 'Чайник DEXP KG-1700Wave',
            'color': 'коричневый',
            'price': '1050 руб',
            'buyDate': '13.12.2021',
            'buyPlace': 'Казань, Краснококшайская 140, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_11_1.webp', 'electronics/electronics_11_2.webp'],
            'description': `Бюджетный электрический чайник, купил когда старый сломался.`,
        },
        12: {
            'name': 'Микроволновка Horizont 20MW700-1378AAW',
            'color': 'белый',
            'price': '3499 руб',
            'buyDate': '26.02.2019',
            'buyPlace': 'Интернет-магазин rbt.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_12_1.webp', 'electronics/electronics_12_2.webp'],
            'description': `Работала исправно до 2023 года, потом стала запотевать изнутри, приходится вытирать воду,
                            из-за влаги стала появляться ржавчина. Так же от времени ручка таймера в стартовом положении
                            перекосилась влево.`,
        },
        13: {
            'name': 'Наушники Panasonic RP-HS46E',
            'color': 'белый',
            'price': '600 руб',
            'buyDate': '06.01.2022',
            'buyPlace': 'Казань, ТЦ Савиново, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_13_1.png', 'electronics/electronics_13_2.png',
                      'electronics/electronics_13_3.png', 'electronics/electronics_13_4.png'],
            'description': `Бюджетные беспроводные наушники, хорошее качество звука за свои деньги. На ушах держатся
                            хорошо. Служат около года, материалы дешёвые, тонкие провода, за год могут порваться.
                            Амбюшуры за год сильно пачкаются, рвутся, слетают. Крепежи на уши за год разбалтываются.
                            Как бюджетные наушники на год хорошие, как долгоиграющую вещь не стоит рассматривать.
                            Тем не менее заказывал эту модель 5 раз: 19.06.18, 19.11.18, 11.06.19 (2 шт), 06.01.22.`,
        },
        14: {
            'name': 'SSD-накопитель M.2 2280 250Гб Kingston NV1 (SNVS)',
            'color': 'синий',
            'price': '2699 руб',
            'buyDate': '18.10.2022',
            'buyPlace': 'Казань, Декабристов 133, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_14_1.webp'],
            'description': `SSD-накопитель в настольный ПК, купил на смену вышедшему из строя старому SSD.`,
        },
        15: {
            'name': 'Беспроводные наушники Hoco EW02',
            'color': 'белый',
            'price': '899 руб + доставка 149',
            'buyDate': '08.03.2023',
            'buyPlace': 'Яндекс Маркет, магазин HOCO TECHNOLOGY',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_15_1.webp', 'electronics/electronics_15_2.webp',
                      'electronics/electronics_15_3.webp'],
            'description': `Беспроводные наушники с очень хорошим соотношением цена/качество. Заряд держат хорошо,
                            заряжаются от кейса многократно, кейс заряжается от ноутбука быстро.`,
        },
        16: {
            'name': 'Телефон Micromax X088',
            'color': 'чёрный',
            'price': '1000 руб',
            'buyDate': '01.11.2015',
            'buyPlace': 'Ухта',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_16_1.webp', 'electronics/electronics_16_2.webp',
                      'electronics/electronics_16_3.webp'],
            'description': `Простой кнопочный телефон, покупал в армию.`,
        },
        17: {
            'name': 'Телефон Sony Ericsson W700i',
            'color': 'серый',
            'price': '0 руб (достался по наследству)',
            'buyDate': '01.08.2007',
            'buyPlace': 'Ухта',
            'actual': 'кому-то отдал',
            'end': '01.08.2012',
            'photo': ['electronics/electronics_17_1.webp', 'electronics/electronics_17_2.webp',
                      'electronics/electronics_17_3.webp', 'electronics/electronics_17_4.webp',
                      'electronics/electronics_17_5.webp'],
            'description': `Кнопочный телефон, который уже можно назвать смартфоном. Достался по наследству от отчима.
                            На тот момент был чудом техники. Пользовался им до 2012 года, пока он физически не развалился.`,
        },
        18: {
            'name': 'Телефон Siemens M55',
            'color': 'серый/белый/оранжевый',
            'price': '0 руб (достался по наследству)',
            'buyDate': '01.08.2006',
            'buyPlace': 'Ухта',
            'actual': 'кому-то отдал',
            'end': '01.08.2007',
            'photo': ['electronics/electronics_18_1.webp', 'electronics/electronics_18_2.webp'],
            'description': `Кнопочный телефон, достался по наследству от отчима. Отличный для своего времени. Мог
                            прослужить ещё очень много лет, но по наследству всего год спустя достался уже более новый телефон.`,
        },
        19: {
            'name': 'Монитор 31.5 Samsung U32J590UQI [LU32J590UQIXCI]',
            'color': 'чёрный',
            'price': '24799 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_19_1.webp', 'electronics/electronics_19_2.webp',
                      'electronics/electronics_19_3.webp', 'electronics/electronics_19_4.webp'],
            'description': `Лучший монитор до 25К с такой диагональю и разрешением (32 дюйма, 4К). Цветопередача
                            нормальная, яркий, вроде как есть FreeSync (защита глаз от мерцания), угол обзора нормальный.
                            Время отклика среднее, так как я не геймер, то не обращаю на это внимания. Частота 60Гц, что
                            вполне терпимо. Главные минусы - нельзя регулировать высоту монитора и поворот влево/вправо
                            (только вверх/вниз) + после включения экрана начинает глючно моргать, требуется в настройках
                            переключиться на HDMI2, тогда перестаёт глючить (можно и не выключать экран, но тогда при
                            выключенном компьютере он переходит в режим ожидания и начинает моргать световым индикатором).`,
        },
        20: {
            'name': 'Компьютерный корпус Cougar MX330-G',
            'color': 'чёрный',
            'price': '2750 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_20_1.webp', 'electronics/electronics_20_2.jpg', 'electronics/electronics_20_3.webp',
                      'electronics/electronics_20_4.webp', 'electronics/electronics_20_5.webp'],
            'description': `Отличный корпус с боковой стенкой из закалённого стекла, вместительный, есть пространство
                            под любые комплектующиеся, даже специальные выемки под прокладку кабелей.`,
        },
        21: {
            'name': 'Материнская плата ASRock B450M PRO4',
            'color': 'чёрный/серый',
            'price': '6635 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_21.webp'],
            'description': `Игровая материнская плата, брал на вырост, с заделом на будущее. 10.05.2020 сдох один из
                            USB-портов на задней панели.`,
        },
        22: {
            'name': 'Оперативная память Kingston HyperX Fury Red DDR4 DIMM 2666MHz (2х8Gb)',
            'color': 'красный',
            'price': '10291 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_22.webp'],
            'description': `Две планки оперативной памяти с красивыми радиаторами. Немного переплатил за красоту (осознанно).`,
        },
        23: {
            'name': 'Процессор AMD Ryzen 5 2400G YD2400C5M4MFB (3600MHz/AM4/L3 4096Kb) OEM',
            'color': 'серый',
            'price': '11382 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_23.png'],
            'description': `Неплохой OEM процессор (OEM - как есть с завода, т.е. без кулера и коробки) с неплохим
                            встроенным видеоядром.`,
        },
        24: {
            'name': 'SSD диск SmartBuy Jolt 120Gb SB120GB-JLT-25SAT3',
            'color': 'чёрный',
            'price': '1855 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'сдал на переработку',
            'end': '16.10.2022',
            'photo': ['electronics/electronics_24.webp'],
            'description': `Обычный бюджетный SSD, из-за ограниченного бюджета при сборке компьютера взял маленький по
                            объёму и от более бюджетного производителя. Прослужил 4 года, потом вышел из строя и пришлось
                            экстренно покупать замену (к счастью ценных файлов на нём не было).`,
        },
        25: {
            'name': 'HDD диск Seagate ST1000DM010 Barracuda 1Tb',
            'color': 'чёрный',
            'price': '2900 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_25.webp'],
            'description': `Хороший HDD, служит до сих пор.`,
        },
        26: {
            'name': 'Кулер ID-Cooling SE-213V2',
            'color': 'чёрный',
            'price': '1006 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_26_1.webp', 'electronics/electronics_26_2.webp',
                      'electronics/electronics_26_3.webp', 'electronics/electronics_26_4.webp',
                      'electronics/electronics_26_5.webp'],
            'description': `Обычный кулер, с охлаждением справляется. Подходит для моделей процессора
                            Intel LGA1150/1155/1156/775/AMD FM2+/FM2/FM1/AM3+/AM3/AM2+/AM2`,
        },
        27: {
            'name': 'Клавиатура A4Tech KV-300H Dark Grey USB',
            'color': 'серый',
            'price': '1450 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_27_1.webp', 'electronics/electronics_27_2.webp'],
            'description': `Неплохая бюджетная клавиатура. Нормальный ход клавиш, не громкая, со световыми индикаторами
                            (Cups Lock, Num Pad), с двумя USB-портами (через клавиатуру к компу можно подключить мышку
                            и флешку), устойчивая (не елозит по столу).`,
        },
        28: {
            'name': 'Блок питания BEQUIET Pure Power 10 300 Вт ATX BN270 Bronze',
            'color': 'чёрный',
            'price': '3200 руб',
            'buyDate': '06.11.2018',
            'buyPlace': 'Интернет-магазин onlinetrade.ru',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_28_1.jpg', 'electronics/electronics_28_2.jpg'],
            'description': `Хороший блок питания от именитой фирмы. Покупался под текущую конфигурацию компьютера с
                            небольшим запасом (видеокарта отсутствует), при покупке видеокарты 100% потребуется замена
                            блока питания, иначе мощности не хватит.`,
        },
        29: {
            'name': 'Проводная мышь A4Tech Bloody V8',
            'color': 'чёрный',
            'price': '1499 руб',
            'buyDate': '13.12.2021',
            'buyPlace': 'Казань, Краснококшайская 140, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_29_1.webp', 'electronics/electronics_29_2.webp',
                      'electronics/electronics_29_3.webp'],
            'description': `Неплохая мышь с подсветкой, длинный провод, есть несколько скоростей, есть дополнительные
                            кнопки. Покупал по необходимости, когда вышла из строя старая мышь, отслужившая 10 лет.
                            Через несколько месяцев эксплуатации мышь начала издавать жуткий писк, в сети пишут что
                            из-за того, что на мышь поступает избыточное напряжение, а производитель сэкономил на
                            конденсаторах (не поставил их в мышь) и лишней энергии некуда было деваться, так как мышь
                            потребляет меньше энергии, чем на неё поступает с ПК) и вроде как это часто встречаемый
                            брак этой серии. По гарантии заменил мышь в магазине (10.11.2022), больше проблем с ней не было.`,
        },
        30: {
            'name': 'Обогреватель Electrolux EOH/M-5157N',
            'color': 'белый',
            'price': '3699 руб + 300 доставка',
            'buyDate': '08.06.2023',
            'buyPlace': 'Казань, ТЦ Парк Хаус, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_30_1.webp', 'electronics/electronics_30_2.webp',
                      'electronics/electronics_30_3.webp', 'electronics/electronics_30_4.webp',
                      'electronics/electronics_30_5.webp'],
            'description': `Небольшой напольный обогреватель, по мощности для обогрева небольшой комнаты. Подарок мамы.`,
        },
        31: {
            'name': 'Весы напольные GALAXY GL4850',
            'color': 'чёрный',
            'price': '1534 руб',
            'buyDate': '15.10.2017',
            'buyPlace': 'Казань, Краснококшайская 140, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_31_1.webp', 'electronics/electronics_31_2.webp',
                      'electronics/electronics_31_3.webp'],
            'description': `Напольные весы для измерения веса, максимальный вес 180 кг, погрешность измерений - 100 гр.
                            Показывают так же процент жира, мышц, вес воды и костной массы, необходимое количество
                            килокалорий в сутки и индекс массы тела (ИМТ). Погрешность небольшая (производителем заявлено
                            100 гр). Есть настройки, позволяющие сохранять несколько профилей (для каждого профиля можно
                            указать свой пол, возраст и рост, что автоматически скорректирует показатели). Батарейки
                            хватает надолго. В целом неплохие весы.`,
        },
        32: {
            'name': 'Весы кухонные DEXP PT-25L',
            'color': 'светло-серый',
            'price': '550 руб',
            'buyDate': '29.04.2018',
            'buyPlace': 'Казань, Краснококшайская 140, магазин DNS',
            'actual': 'в наличии',
            'photo': ['electronics/electronics_32_1.webp', 'electronics/electronics_32_2.webp'],
            'description': `Кухонные весы для еды, максимальный вес 5 кг, погрешность измерений - 1 гр.`,
        },
        33: {
            'name': 'Телевизор TELEFUNKEN TF-LED32S39T2S',
            'color': 'светло-серый',
            'price': '11000 руб + 2000 гарантия на 2 года',
            'buyDate': '15.10.2017',
            'buyPlace': 'Казань, Краснококшайская 140, магазин DNS',
            'actual': 'продали',
            'end': '27.12.2020',
            'photo': ['electronics/electronics_33_1.webp', 'electronics/electronics_33_2.webp',
                      'electronics/electronics_33_3.webp'],
            'description': `Бюджетный телевизор, небольшой экран, разрешение HD, частота 50 Гц, матрица TF LED (так себе
                            цветопередача). Продал через 3 года за ненадобностью за 6000 руб.`,
        },
        34: {
            'name': 'Ноутбук ASUS (A52J) iCore3',
            'color': 'серый/чёрный',
            'price': '30000 руб',
            'buyDate': '15.08.2011',
            'buyPlace': 'Ухта',
            'actual': 'продал',
            'end': '15.07.2017',
            'photo': ['electronics/electronics_34_1.jpg', 'electronics/electronics_34_2.jpg',
                      'electronics/electronics_34_3.jpg', 'electronics/electronics_34_4.jpg',
                      'electronics/electronics_34_5.jpg', 'electronics/electronics_34_6.jpg',
                      'electronics/electronics_34_7.jpg', 'electronics/electronics_34_8.jpg',
                      'electronics/electronics_34_9.jpg'],
            'description': `Хороший ноутбук с неплохим железом, покупали перед первым курсом университета. Подарок мамы.
                            Прослужил до лета 2017 года, когда уже села батарея, сильно тормозил и глючил. Продал
                            сослуживцу за 2000 руб, так как ноутбук однозначно требовал ремонта и вложения средств.`,
        },
    },
    'sport': {
        1: {
            'name': 'Набор кистевых эспандеров "Эспандеры Воронцова"',
            'color': 'зелёный/синий/чёрный',
            'price': '949 руб',
            'buyDate': '29.11.2022',
            'buyPlace': 'Ozon, магазин Эспандеры Воронцова',
            'actual': 'в наличии',
            'photo': ['sport/sport_1_1.jpg', 'sport/sport_1_2.jpg'],
            'description': `Заказывал через Ozon, 5 штук: 30 кг (зелёный), 40 кг (чёрный), 50 кг (синий с рельефным
                            рисунком панды WWF), 60 кг (чёрный), 80 кг (чёрный с рельефным рисунком летучей мыши (знак
                            бэтмена))`,
        },
        2: {
            'name': 'Турник/брусья',
            'color': 'чёрный',
            'price': '2790 руб + установка около 1000',
            'buyDate': '22.06.2019',
            'buyPlace': 'Казанская частная мастерская',
            'actual': 'в наличии',
            'photo': ['sport/sport_2.jpg'],
            'description': `Заказывал в Казани с доставкой по городу, мастера для установки нашёл отдельно.`,
        },
        3: {
            'name': 'Горный (MTB) велосипед Giant Escaper Disc',
            'color': 'чёрный',
            'price': '9960 руб',
            'buyDate': '24.06.2008',
            'buyPlace': 'Ухта, ТЦ Север, магазин Спортлидер',
            'actual': 'продали',
            'end': '10.07.2023',
            'photo': ['sport/sport_3_1.webp', 'sport/sport_3_2.jpg', 'sport/sport_3_3.jpg', 'sport/sport_3_4.jpg'],
            'description': `В Ухте ещё в школе покупали на каникулах летом. Фактически не совсем горный, а гибрид горного
                            с городским. Последний раз катался на нём в августе 2019, потом стоял несколько лет на балконе.
                            Когда при продаже квартиры расхламляли балкон продали его 10.07.2023`,
        },
        4: {
            'name': 'Горный (MTB) велосипед STELS Navigator 650 MD 27.5 V030 (2017)',
            'color': 'чёрный',
            'price': '18690 руб',
            'buyDate': '23.06.2018',
            'buyPlace': 'Казань, Чистопольская 7, магазин Велолига',
            'actual': 'в наличии',
            'photo': ['sport/sport_4.webp'],
            'description': `Отличный велосипед, лучшее что можно купить в бюджете до 20 тысяч (на момент 2018 года).
                            Лёгкий для своих габаритов (за счёт алюминиевой рамы), колёса большие, обвес нормального
                            качества, для города + редких вылазок за город идеально подходит.`,
        },
        5: {
            'name': 'Гиря Domyos на 16 кг',
            'color': 'чёрный',
            'price': '3299 руб',
            'buyDate': '28.11.2019',
            'buyPlace': 'Казань, Ибрагимова 54, магазин Decathlon',
            'actual': 'в наличии',
            'photo': ['sport/sport_5_1.webp', 'sport/sport_5_2.webp'],
            'description': `Хорошая прорезиненая гиря, ручка квадратной формы, вполне удобно.`,
        },
        6: {
            'name': 'Гиря уральская чемпионская GCH-38 на 38 кг',
            'color': 'серый',
            'price': '6300 руб (скидка 4904) + доставка 799',
            'buyDate': '20.07.2022',
            'buyPlace': 'Яндекс Маркет, магазин СпортОснова',
            'actual': 'в наличии',
            'photo': ['sport/sport_6.jpg'],
            'description': `Хорошая цельнолитая богатырская гиря. Полностью повторяют форму "тела" и форму ручки
                            соревновательных гирь ВФГС. Изначально стоила 12503 руб, но была скидка почти 50% + купон
                            от Яндекс Маркета на 500 руб.`,
        },
        7: {
            'name': 'Аппликатор Кузнецова (2 шт)',
            'color': 'серый',
            'price': '944 руб',
            'buyDate': '01.05.2023',
            'buyPlace': 'Ozon, магазин Лаборатория Кузнецова',
            'actual': 'в наличии',
            'photo': ['sport/sport_7_1.webp', 'sport/sport_7_2.webp'],
            'description': `Два массажных акупунктурных валика. Ткань из натурального льна, шипы из специального пластика
                            с магнитными вставками. Валик побольше с красными менее острыми иглами - для поясницы, а валик
                            поменьше с жёлтыми более острыми иглами - для шеи.`,
        },
    },
    'dishes': {
         1: {
            'name': 'Сковорода Kukmara',
            'color': 'чёрный',
            'price': '1601 руб',
            'buyDate': '04.06.2023',
            'buyPlace': 'Wildberries, магазин Kukmara',
            'actual': 'в наличии',
            'photo': ['dishes/dishes_1.webp'],
            'description': `Большая сковорода с крышкой в комплекте. Антипригарное покрытие, но мыть нужно аккуратно,
                            без металлической сеточки.`,
        },
        2: {
            'name': 'Сковорода Kukmara',
            'color': 'чёрный',
            'price': '1540 руб',
            'buyDate': '04.06.2023',
            'buyPlace': 'Wildberries, магазин Kukmara',
            'actual': 'в наличии',
            'photo': ['dishes/dishes_2_1.jpg', 'dishes/dishes_2_2.webp'],
            'description': `Маленькая сковорода без крышки. Крышку докупил отдельно за 332 руб. Антипригарное покрытие,
                            но мыть нужно аккуратно, без металлической сеточки.`,
        },
        3: {
            'name': 'Кастрюля-ковш Kukmara',
            'color': 'чёрный',
            'price': '1463 руб',
            'buyDate': '15.06.2023',
            'buyPlace': 'Wildberries, магазин Kukmara',
            'actual': 'в наличии',
            'photo': ['dishes/dishes_3.webp'],
            'description': `Кастрюля-ковш с крышкой на 1,5 литра. Цельнолитая, формовка приятная на ощупь. Антипригарное
                            покрытие, но мыть нужно аккуратно, без металлической сеточки. Оказалась, что не вмещает
                            десяток яиц.`,
        },
        4: {
            'name': 'Кастрюля Kukmara',
            'color': 'чёрный',
            'price': '1383 руб',
            'buyDate': '15.06.2023',
            'buyPlace': 'Wildberries, магазин Kukmara',
            'actual': 'в наличии',
            'photo': ['dishes/dishes_4.webp'],
            'description': `Кастрюля с крышкой на 2 литра. Цельнолитая, формовка приятная на ощупь. Антипригарное
                            покрытие, но мыть нужно аккуратно, без металлической сеточки.`,
        },
    },
    'other': {
        1: {
            'name': 'Фильтр-кувшин Аквафор Прованс А5',
            'color': 'прозрачный/белый',
            'price': '899 руб',
            'buyDate': '30.01.2023',
            'buyPlace': 'Ozon',
            'actual': 'в наличии',
            'photo': ['other/other_1_1.webp', 'other/other_1_2.webp'],
            'description': `1 фильтр в комплекте, заказывал на Ozon.`,
        },
        2: {
            'name': 'Маска для ныряния',
            'color': 'прозрачный/серо-бирюзовый',
            'price': '399 руб',
            'buyDate': '23.07.2021',
            'buyPlace': 'Казань, Ибрагимова 54, магазин Decathlon',
            'actual': 'в наличии',
            'photo': ['other/other_2.png'],
            'description': `Маска для ныряния и плавания.`,
        },
        3: {
            'name': 'Плечики для одежды',
            'color': 'чёрный',
            'price': '302 руб',
            'buyDate': '16.06.2023',
            'buyPlace': 'Wildberries, магазин ELFE',
            'actual': 'в наличии',
            'photo': ['other/other_3.webp'],
            'description': `Пластиковые чёрные плечики для одежды, 3 штуки.`,
        },
        4: {
            'name': 'Напольная вешалка',
            'color': 'металлик',
            'price': '1125 руб',
            'buyDate': '16.06.2023',
            'buyPlace': 'Wildberries, магазин MIA мебель',
            'actual': 'в наличии',
            'photo': ['other/other_4.jpg'],
            'description': `Сборная напольная вешалка.`,
        },
        5: {
            'name': 'Комплект постельного белья АРТПОСТЕЛЬ',
            'color': 'бежевый',
            'price': '2017 руб',
            'buyDate': '08.05.2023',
            'buyPlace': 'Ozon, магазин АРТПОСТЕЛЬ',
            'actual': 'в наличии',
            'photo': ['other/other_5.webp'],
            'description': `2-x спальный комплект постельного белья, рисунок круги и волнистые линии.`,
        },
        6: {
            'name': 'Комплект постельного белья АРТПОСТЕЛЬ',
            'color': 'бежевый',
            'price': '1852 руб',
            'buyDate': '08.05.2023',
            'buyPlace': 'Ozon, магазин АРТПОСТЕЛЬ',
            'actual': 'в наличии',
            'photo': ['other/other_6.webp'],
            'description': `1,5-ра спальный комплект постельного белья, рисунок в клетку.`,
        },
        7: {
            'name': 'Полотенце махровое',
            'color': 'синий',
            'price': '869 руб',
            'buyDate': '08.05.2023',
            'buyPlace': 'Ozon, магазин Karna',
            'actual': 'в наличии',
            'photo': ['other/other_7.webp'],
            'description': `Комплект из двух махровых полотенец для ванной Karna LADIN.`,
        },
        8: {
            'name': 'Полотенце махровое',
            'color': 'светло-коричневый (капучино)',
            'price': '869 руб',
            'buyDate': '08.05.2023',
            'buyPlace': 'Ozon, магазин Karna',
            'actual': 'в наличии',
            'photo': ['other/other_8.webp'],
            'description': `Комплект из двух махровых полотенец для ванной Karna LADIN.`,
        },
    },
}
